EnterpriseWechat:
  CorpID: ''
  CorpSecret: ''
  AgentID: ''
  Token: ''
  EncodingAESKey: ''
  ManagerID: '@all'
  TokenApi: https://qyapi.weixin.qq.com/cgi-bin/gettoken
  PushApi: https://qyapi.weixin.qq.com/cgi-bin/message/send
Others:
  #此微信服务后台的访问地址，格式 http(s)://xxx.xxx.xxx:port
  WxHost: ''
  #必须，TMDB的apikey，官网注册申请 https://www.themoviedb.org/
  TMDBApiKey: ''
  #暂未使用
  Proxy: ''
  #图片缓存服务，以便手机可以正常访问TVDB等网站的图片，格式 http(s)://xxx.xxx.xxx:port
  #访问 https://github.com/Oscar1011/image-server-node 进行配置
  #留空则会直接使用TMDB/TVDB等图片链接进行推送，国内网络环境可能无法加载显示
  ImageServer: ''
Sonarr:
  #Sonarr访问地址，格式 http(s)://xxx.xxx.xxx:port
  Host: ''
  #Sonarr apikey
  ApiKey: ''
  #Sonarr添加剧集时的存放路径
  RootDir: ''
  #影片质量，进入Settings->Profiles，支持配置为Quality Profiles对应name，如Any，不建议使用含空格的名称
  QualityProfileId: Any
  SeasonFolder: True
  Monitored: True
  #语言参数，进入Settings->Profiles，支持配置为Language Profiles对应name，如English，不建议使用含空格的名称
  LanguageProfileId: English
  #添加时是否搜索缺少的剧集
  SearchForMissingEpisodes: True
Radarr:
  #Radarr 访问地址，格式 http(s)://xxx.xxx.xxx:port
  Host: ''
  #Radarr apikey
  ApiKey: ''
  #影片质量，进入Settings->Profiles，支持配置为Quality Profiles对应name，如Any，不建议使用含空格的名称
  QualityProfileId: Any
  RootDir: ''
  Monitored: True
  Search: True
  MinimumAvailability: "announced"
Service:
  Host: 0.0.0.0
  #服务端口
  Port: 8000
